//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APUPayWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APUUser
    {
        public string user_id { get; set; }
        public string user_password { get; set; }
        public string user_email { get; set; }
        public string user_type { get; set; }
        public string full_name { get; set; }
        public Nullable<decimal> user_balance { get; set; }
    }
}
